---
title: "Compile & Export Data"
date: "`r format(Sys.Date(), '%Y-%b-%d')`"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup, echo=FALSE, include=FALSE}

library(calval)
library(dplyr)
library(DT)
library(ggplot2)
library(here)
library(lubridate)
library(plotly)
library(readr)
library(sensorstrings)
library(shiny)
library(stringr)
library(tidyr)

dt_options <- list(
  dom = 'Bft',
  paging = TRUE,
  searching = TRUE,
  scrollY = "500px",
  buttons = c('copy', 'csv'),
  columnDefs = list(list(className = 'dt-center', targets = "_all"))
)
```


```{r}
#########################################
###### Reactive UI ###################### 
#########################################

output$compile_button <- renderUI({
  req(input$upload)
  
  actionButton(
    "compile", "Compile Data", 
    width = '100%',
    onclick = "location.href='#section-compiled-data';")
})

output$trim_start <- renderUI({
  dat <- compile_data()
  textInput(
    "ts_start", "First Good Timestamp",
    value = min(dat$timestamp_utc),
    width = '100%'
  )
})

output$trim_end <- renderUI({
  dat <- compile_data()
  textInput(
    "ts_end", "Last Good Timestamp",
    value = max(dat$timestamp_utc),
    width = '100%'
  )
})

output$trim_button <- renderUI({
  req(input$compile)
  actionButton(
    "apply_trim", 
    "Trim", 
    width = '100%',
    onclick = "location.href='#section-trimmed-data';")
})

output$val_button <- renderUI({
  req(input$compile)
  req(input$apply_trim)
  req(input$data_type == "Validation")
  
  actionButton(
    "apply_val", "Validate", 
    width = '100%',
    onclick = "location.href='#section-sensor-validation';")
})

#########################################
###### Data Wrangling ################### 
#########################################

get_files <- reactive({
  req(input$upload)
  files <- unzip(input$upload$datapath, list = FALSE)
  files <- files[grep(".csv", files)]
  
  return(files)
})

read_log <- reactive({
  req(input$upload)
  
  zip_files <- get_files()
  path <- zip_files[grep("log", zip_files)]
  
  ss_log <- ss_read_log(path, parse = FALSE, verbose = FALSE)
  
  return(ss_log)
})

compile_data <- eventReactive(input$compile, {
  
  zip_files <- get_files()
  
  depl_log <- read_log() %>% ss_parse_log(verbose = FALSE)
  depl_dates <- depl_log$deployment_dates
  sn_table <- depl_log$sn_table
  
  depl_data <- tibble(NULL)
  
  sn_am <- sn_table %>%
    filter(str_detect(log_sensor, regex("aquameasure", ignore_case = TRUE)))
  if(nrow(sn_am) > 0) {
    am <- ss_compile_aquameasure_data(
      path = zip_files[grep("aquameasure", zip_files)],
      sn_table = sn_table,
      deployment_dates = depl_dates,
      trim = TRUE
    )
    depl_data <- bind_rows(depl_data, am)
  }
  
  sn_hobo <- sn_table %>%
    filter(str_detect(log_sensor, regex("hobo", ignore_case = TRUE)))
  if(nrow(sn_hobo) > 0) {
    hobo <- ss_compile_hobo_data(
      path = zip_files[grep("hobo", zip_files)],
      sn_table = sn_table,
      deployment_dates = depl_dates,
      trim = TRUE
    )
    depl_data <- bind_rows(depl_data, hobo)
  }
  
  sn_tidbit <- sn_table %>%
    filter(str_detect(log_sensor, regex("tidbit", ignore_case = TRUE)))
  if (nrow(sn_tidbit) > 0) {
    tidbit <- ss_compile_hobo_data(
      path = zip_files[grep("tidbit", zip_files)],
      sn_table = sn_tidbit,
      deployment_dates = depl_dates,
      trim = TRUE,
      sensor_make = "tidbit"
    )
    depl_data <- bind_rows(depl_data, tidbit)
  }
  
  sn_vem <- sn_table %>%
    filter(str_detect(log_sensor, regex("VR2AR", ignore_case = TRUE)))
  if (nrow(sn_vem) > 0) {
    vemco <- ss_compile_vemco_data(
      path = zip_files[grep("vemco", zip_files)],
      sn_table = sn_vem,
      deployment_dates = depl_dates,
      trim = TRUE
    )
    depl_data <- bind_rows(depl_data, vemco)
  }
  
  return(depl_data)
})


observeEvent(input$compile, {
  showModal(
    modalDialog(
      "Compiling data. This may take several minutes",
      easyClose = TRUE
    ))
})  


trim_data <- eventReactive(input$apply_trim, {
  ts_min <- input$ts_start
  ts_max <- input$ts_end
  
  dat <- compile_data() %>% 
    filter(timestamp_utc >= ts_min, timestamp_utc <= ts_max) 

  return(dat)
})


val_data <- eventReactive(input$apply_val, {
  dat <- trim_data() %>% 
    ss_pivot_longer() %>% 
    cv_round_timestamps() %>%
    cv_assign_tolerance_flag()

  return(dat)
})

#########################################
###### Figures & Tables ################## 
#########################################

ts_click <- reactive({
  req(input$compile)
  
  ts_info <- event_data("plotly_click", source = "plot1")
  
  if (is.null(ts_info)) {
      "Click a point from the chart above to print its timestamp. Double click the chart to clear."
  } else {
    ts_new <- data.frame(ts = as_datetime(ts_info$x))
    ts_new$ts <- format(ts_new$ts, "%Y-%m-%d %H:%M:%S")
    
    ts_new$ts
  }
  
})

customize_fig <- reactive({
  req(input$data_type)
  
  if(input$data_type == "Validation") {
    point_col <- "sensor_serial_number"
    point_size <- 1
  }
  if(input$data_type == "Deployment") {
    point_col <- "sensor_depth_at_low_tide_m"
    point_size <- 0.25
  }
  
  return(data.frame(point_col = point_col, point_size = point_size))
  
})


plot_data_sn <- reactive({
  dat <- val_data() %>% 
    mutate(sensor_serial_number = factor(sensor_serial_number))
  
  p <- cv_plot_flags(dat, colour_col = "sensor_serial_number")
  
  return(p)
})

```


Column {.sidebar data-width=350}
=======================================

```{r}
selectInput(
  "data_type", 
  "Select Data Type", 
  choices = c("Deployment", "Validation"),
  width = '100%'
)

fileInput(
  "upload",
  "Upload Zip File:",
  accept = ".zip",
  buttonLabel = "Upload Data",
  multiple = FALSE,
  width = '100%'
)

uiOutput("compile_button")
HTML("<br>")

uiOutput("trim_start")

uiOutput("trim_end")

uiOutput("trim_button")
HTML("<br>")

uiOutput("val_button")

```

Instructions {data-icon="fa-circle-info"}
=======================================

Explanation


Compiled Data {data-icon="fa-table"}
=======================================

Col {.tabset}
-------------------------------------

### Figure
```{r}

output$p_raw <- renderPlotly({
  
  validate(need(input$compile, "No data to plot"))
  
  dat <- compile_data()
  
  fig_params <- customize_fig()
  
  p <- ss_ggplot_variables(
    dat, 
    color_col = fig_params$point_col, 
    point_size = fig_params$point_size, 
    axis_label_newline = FALSE
  )
  
  p <- ggplotly(p, tooltip = "text", source = "plot1") #%>%
    # config(
    #   modeBarButtonsToRemove = list("toggleSpikelines", "autoScale2d"),
    #   displaylogo = FALSE,
    #   toImageButtonOptions = list(
    #     format = "png",
    #     filename = "temperature_validation",
    #     width = 900, height = 500
    #   ))  %>%
    # layout(margin = list(b = 90, l = 90)) 
  
 # p <- event_register(p, 'plotly_click')
  
  p
})

plotlyOutput("p_raw")
```

### Data
```{r}
renderDT({
  validate(need(input$compile, "No data to plot"))

  compile_data() %>%
    datatable(
      extensions = 'Buttons',
      options = dt_options,
      rownames = FALSE)
})
```

### Log
```{r}
renderDT({
  validate(need(input$compile, "No data to plot."))

  read_log() %>%
    datatable(
      extensions = 'Buttons',
      options = dt_options,
      rownames = FALSE)
})
```

### Uploaded Files
```{r}
renderPrint({
  validate(need(input$upload, "No files uploaded"))
  get_files()
})
```

Col {data-height=50}
-------------------------------------

### Print Timestamp
```{r}
renderText(ts_click())
```


Trimmed Data {data-icon="fa-scissors"}
=======================================

Col {.tabset}
-------------------------------------

### Trimmed Data 
```{r}

renderPlotly({
  validate(need(input$apply_trim, "No trimmed data to plot"))
  
  dat <- trim_data()
  
  fig_params <- customize_fig()
  
  p <- ss_ggplot_variables(
    dat, 
    color_col = fig_params$point_col, 
    point_size = fig_params$point_size, 
    axis_label_newline = FALSE
  )
  
  p <- ggplotly(p, tooltip = "text") #%>%
    # config(
    #   modeBarButtonsToRemove = list("toggleSpikelines", "autoScale2d"),
    #   displaylogo = FALSE,
    #   toImageButtonOptions = list(
    #     format = "png",
    #     filename = "temperature_validation",
    #     width = 900, height = 500
    #   ))  %>%
    # layout(margin = list(b = 90, l = 90)) 
  
 # p <- event_register(p, 'plotly_click')
  
  p
})


```

### Data 
```{r}
renderDT({
  validate(need(input$apply_trim, "No trimmed data"))

  trim_data() %>%
    datatable(
      extensions = 'Buttons',
      options = dt_options,
      rownames = FALSE
    )
})
```



Sensor Validation {data-icon="fa-check"}
=======================================

Row {.tabset} 
-------------------------------------

### Temperature
```{r}

renderPlotly({
  validate(need(input$apply_trim, "No validation data to plot"))
  validate(need(input$data_type == "Validation", "No validation data to plot. Please choose 'Validation' from the 'Select Data Type' dropdown"))
  validate(need(input$apply_val, "No validation data to plot. Please click the 'Validate' button"))
  
  p_temp <- plot_data_sn()
  
  validate(
    need("temperature_degree_c" %in% names(p_temp), "No temperature data found"))
  
  ggplotly(p_temp$temperature_degree_c) %>%
    config(
      modeBarButtonsToRemove = list("toggleSpikelines", "autoScale2d"),
      displaylogo = FALSE,
      toImageButtonOptions = list(
        format = "png",
        filename = "temperature_validation",
        width = 900, height = 500
      ))  %>%
    layout(margin = list(b = 90, l = 90))
})

```


### Dissolved Oxygen
```{r}

renderPlotly({
  validate(need(input$apply_trim, "No validation data to plot"))
  validate(need(input$data_type == "Validation", "No validation data to plot. Please choose 'Validation' from the 'Select Data Type' dropdown"))
  validate(need(input$apply_val, "No validation data to plot. Please click the 'Validate' button"))
  
  p_do <- plot_data_sn()
  
  validate(
    need("dissolved_oxygen_percent_saturation" %in% names(p_do), 
         "No dissolved oxygen data found")
  )
  
  ggplotly(p_do$dissolved_oxygen_percent_saturation) %>%
    config(
      modeBarButtonsToRemove = list("toggleSpikelines", "autoScale2d"),
      displaylogo = FALSE,
      toImageButtonOptions = list(
        format = "png",
        filename = "dissolved_oxygen_percent_saturation_validation",
        width = 900, height = 500
      ))  #%>%
  #layout(margin = list(b = 90, l = 90))
})

``` 


### Salinity

```{r}

renderPlotly({
  validate(need(input$apply_trim, "No validation data to plot"))
  validate(need(input$data_type == "Validation", "No validation data to plot. Please choose 'Validation' from the 'Select Data Type' dropdown"))
  validate(need(input$apply_val, "No validation data to plot. Please click the 'Validate' button"))
  
  p_sal <- plot_data_sn()
  
  validate(need("salinity_psu" %in% names(p_sal), "No salinity data found"))
  
  ggplotly(p$salinity_psu) %>%
    config(
      modeBarButtonsToRemove = list("toggleSpikelines", "autoScale2d"),
      displaylogo = FALSE,
      toImageButtonOptions = list(
        format = "png",
        filename = "salinity_validation",
        width = 900, height = 500)
    ) 
})

``` 

### Validation Data

```{r}
renderDT({
  validate(need(input$apply_trim, "No validation data to show"))
  validate(need(input$data_type == "Validation", "No validation data to show. Please choose 'Validation' from the 'Select Data Type' dropdown"))
  validate(need(input$apply_val, "No validation data to show. Please click the 'Validate' button"))

  val_data() %>%
    datatable(
      extensions = 'Buttons',
      options = dt_options,
      rownames = FALSE
    )
})
```

### Results

```{r}
renderDT({
    validate(need(input$apply_trim, "No validation results to show"))
  validate(need(input$data_type == "Validation", "No validation results to show. Please choose 'Validation' from the 'Select Data Type' dropdown"))
  validate(need(input$apply_val, "No validation results to show. Please click the 'Validate' button"))
  
  val_data() %>% 
    cv_summarise_flags(dt = FALSE)  %>% 
    datatable(
      extensions = 'Buttons',
      options = dt_options, 
      rownames = FALSE
    )
})
```

