---
title: "Sensor Validation"
date: "`r format(Sys.Date(), '%Y-%b-%d')`"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup, echo=FALSE, include=FALSE}

library(calval)
#library(deps)
library(dplyr)
library(DT)
#library(googlesheets4) 
library(ggplot2)
library(here)
library(plotly)
library(readr)
library(shiny)
library(tidyr)

```


Cal Val Data {data-icon="fa-chart-line"}
=======================================

Column {.sidebar}
-------------------------------------

```{r}

fileInput(
  "upload",
  "Click here to upload calval data:",
  accept = ".csv",
  buttonLabel = "Upload Data",
  multiple = TRUE,
)

uiOutput("download_ui")
```

```{r}

load_data <- reactive({
  validate(need(input$upload != "", "Please upload data"))
  req(input$upload)
  
  ext <- tools::file_ext(input$upload$name)
  
  if(ext != "csv") {
    validate("Invalid file; Please upload a .csv file")
  }

  dat <- read_csv(input$upload$datapath, show_col_types = FALSE) %>% 
    mutate(sensor_serial_number = factor(sensor_serial_number))
  
  return(dat)
  
})


plot_data_sn <- reactive({
  dat <- load_data()
  
  p <- cv_plot_flags(dat, colour_col = "sensor_serial_number")
  
  return(p)
})


output$download_ui <- renderUI({
  downloadButton(
    "download_button",
    "Download Summary", 
    style = "color: #fff; background-color: #000000; border-color: #2e6da4; width:100%")
    #style = "color: #fff; background-color: #337ab7; border-color: #2e6da4; width:100%")
})

output$download_button <- downloadHandler(
  filename = function() {
    "validation_summary.csv"
  },
  content = function(file) {
    write_csv(
      load_data() %>% 
        cv_summarise_flags(dt = FALSE), file)
  }
)

```


Row {.tabset} 
-------------------------------------

### Temperature
```{r}

renderPlotly({
  
  p_temp <- plot_data_sn()
  
  validate(
    need("temperature_degree_c" %in% names(p_temp), "No temperature data found")
  )
  
  ggplotly(p_temp$temperature_degree_c) %>%
    config(
      modeBarButtonsToRemove = list("toggleSpikelines", "autoScale2d"),
      displaylogo = FALSE,
      toImageButtonOptions = list(
        format = "png",
        filename = "temperature_validation",
        width = 900, height = 500
      ))  %>%
    layout(margin = list(b = 90, l = 90))
})

```


### Dissolved Oxygen
```{r}

renderPlotly({
  
  p_do <- plot_data_sn()
  
  validate(
    need("dissolved_oxygen_percent_saturation" %in% names(p_do), 
         "No dissolved oxygen data found")
  )
  
  ggplotly(p_do$dissolved_oxygen_percent_saturation) %>%
    config(
      modeBarButtonsToRemove = list("toggleSpikelines", "autoScale2d"),
      displaylogo = FALSE,
      toImageButtonOptions = list(
        format = "png",
        filename = "dissolved_oxygen_percent_saturation_validation",
        width = 900, height = 500
      ))  #%>%
  #layout(margin = list(b = 90, l = 90))
})

``` 


### Salinity

```{r}

renderPlotly({
  
  p_sal <- plot_data_sn()
  
  validate(need("salinity_psu" %in% names(p_sal), "No salinity data found"))
  
  ggplotly(p$salinity_psu) %>%
    config(
      modeBarButtonsToRemove = list("toggleSpikelines", "autoScale2d"),
      displaylogo = FALSE,
      toImageButtonOptions = list(
        format = "png",
        filename = "salinity_validation",
        width = 900, height = 500)
    ) # %>%
  #layout(margin = list(b = 90, l = 90))
})

``` 

### Table

```{r}

renderDT({
  load_data() %>% 
    cv_summarise_flags(dt = TRUE)
})
```


`r knitr::knit_exit()`







