---
title: "Compile & Export Data"
date: "`r format(Sys.Date(), '%Y-%b-%d')`"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup, echo=FALSE, include=FALSE}

library(calval)
library(dplyr)
library(DT)
library(ggplot2)
library(here)
library(lubridate)
library(plotly)
library(readr)
library(sensorstrings)
library(shiny)
library(tidyr)

dt_options <- list(
  dom = 'Bft',
  paging = FALSE,
  searching = TRUE,
  scrollY = "500px",
  buttons = c('copy', 'csv'),
  columnDefs = list(list(className = 'dt-center', targets = "_all"))
)

```


```{r}
#########################################
###### Reactive UI ###################### 
#########################################

output$compile_button <- renderUI({
  actionButton(
    "compile", "Import & Compile", 
    width = '100%',
    onclick = "location.href='#section-compiled-data';")
})


output$trim_start <- renderUI({
  dat <- compile_data()
  textInput(
    "ts_start", "First Good Timestamp",
    value = min(dat$timestamp_utc)
  )
})

output$trim_end <- renderUI({
  dat <- compile_data()
  textInput(
    "ts_end", "Last Good Timestamp",
    value = max(dat$timestamp_utc)
  )
})

output$trim_button <- renderUI({
  req(input$compile)
  actionButton(
    "apply_trim", 
    "Trim", 
    width = '100%',
    onclick = "location.href='#section-trimmed-data';")
})

output$val_button <- renderUI({
  req(input$compile)
  req(input$apply_trim)
  req(input$data_type == "Validation")
  
  actionButton(
    "apply_val", "Validate", 
    width = '100%',
    onclick = "location.href='#section-sensor-validation';")
})

#########################################
###### Data Wrangling ################### 
#########################################

file_path <- reactive({
  path <- paste0(here("data"), "/", input$val_id)
  return(path)
})
  

compile_data <- eventReactive(input$compile, {
  path <- file_path()
  validate(need(path != "", "Please choose a folder"))
  
  dat_raw <- ss_compile_deployment_data(path) %>%
    select(
      -c(county, waterbody, station, lease, latitude, longitude,
         string_configuration), 
      -contains("sensor_depth_measured")
    ) %>% 
    mutate(validation_id = input$val_id) %>% 
    relocate(validation_id)
})

trim_data <- eventReactive(input$apply_trim, {
  ts_min <- input$ts_start
  ts_max <- input$ts_end
  
  dat <- compile_data() %>% 
    filter(timestamp_utc >= ts_min, timestamp_utc <= ts_max) 

  return(dat)
})


val_data <- eventReactive(input$apply_val, {
  
  dat <- trim_data() %>% 
    ss_pivot_longer() %>% 
    cv_round_timestamps() %>%
    cv_assign_tolerance_flag()

  return(dat)
})

#########################################
###### Figures & Tables ################## 
#########################################

ts_click <- reactive({
  req(input$compile)
  
  ts_info <- event_data("plotly_click", source = "plot1")
  
  if (is.null(ts_info)) {
      "Click a point from the chart above to print its timestamp. Double click the chart to clear."
  } else {
    ts_new <- data.frame(ts = as_datetime(ts_info$x))
    ts_new$ts <- format(ts_new$ts, "%Y-%m-%d %H:%M:%S")
    
    ts_new$ts
  }
  
})

customize_fig <- reactive({
  req(input$data_type)
  
  if(input$data_type == "Validation") {
    point_col <- "sensor_type"
    point_size <- 1
  }
  if(input$data_type == "Deployment") {
    point_col <- "sensor_depth_at_low_tide_m"
    point_size <- 0.25
  }
  
  return(data.frame(point_col = point_col, point_size = point_size))
  
})


plot_data_sn <- reactive({
  dat <- val_data() %>% 
    mutate(sensor_serial_number = factor(sensor_serial_number))
  
  p <- cv_plot_flags(dat, colour_col = "sensor_serial_number")
  
  return(p)
})

```


Column {.sidebar data-width=300}
=======================================

```{r}
selectInput(
  "data_type", 
  "Select Data Type", 
  choices = c("Deployment", "Validation")
)

selectInput(
  "val_id", 
  "Validation", 
  choices = c("VAL001", "VAL0068", "VAL0069")
)

uiOutput("compile_button")
HTML("<br>")

uiOutput("trim_start")

uiOutput("trim_end")

uiOutput("trim_button")
HTML("<br>")

uiOutput("val_button")

```

Instructions {data-icon="fa-circle-info"}
=======================================

Explanation


Compiled Data {data-icon="fa-table"}
=======================================

Col {.tabset}
-------------------------------------

### Figure
```{r}

output$p_raw <- renderPlotly({
  
  dat <- compile_data()
  
  validate(need(nrow(dat) > 0, "No temperature data found"))
  
  fig_params <- customize_fig()
  
  p <- ss_ggplot_variables(
    dat, 
    color_col = fig_params$point_col, 
    point_size = fig_params$point_size, 
    axis_label_newline = FALSE
  )
  
  p <- ggplotly(p, source = "plot1") #%>%
    # config(
    #   modeBarButtonsToRemove = list("toggleSpikelines", "autoScale2d"),
    #   displaylogo = FALSE,
    #   toImageButtonOptions = list(
    #     format = "png",
    #     filename = "temperature_validation",
    #     width = 900, height = 500
    #   ))  %>%
    # layout(margin = list(b = 90, l = 90)) 
  
 # p <- event_register(p, 'plotly_click')
  
  p
})

plotlyOutput("p_raw")
```

### Data
```{r}
renderDT(
  compile_data() %>% 
    datatable(
      extensions = 'Buttons', 
      options = dt_options, 
      rownames = FALSE)
)
```

Col {data-height=200}
-------------------------------------

### Print Timestamp
```{r}
renderText(ts_click())
```

### Deployment Summary
**Or list files from upload here

```{r}
#renderPrint(get_files())
```

Trimmed Data {data-icon="fa-scissors"}
=======================================

Col {.tabset}
-------------------------------------

### Trimmed Data 
```{r}

renderPlotly({
  dat <- trim_data()
  
  validate(need(nrow(dat) > 0, "No data to plot. Check timestamp inputs"))
  
  p <- ss_ggplot_variables(dat, axis_label_newline = FALSE)
  
  p <- ggplotly(p) #%>%
    # config(
    #   modeBarButtonsToRemove = list("toggleSpikelines", "autoScale2d"),
    #   displaylogo = FALSE,
    #   toImageButtonOptions = list(
    #     format = "png",
    #     filename = "temperature_validation",
    #     width = 900, height = 500
    #   ))  %>%
    # layout(margin = list(b = 90, l = 90)) 
  
 # p <- event_register(p, 'plotly_click')
  
  p
})


```

### Data Table
```{r}
# will be blank until trim applied

renderDT(
  head(trim_data()) %>% 
    datatable(
      extensions = 'Buttons', 
      options = dt_options, 
      rownames = FALSE
    )
)
```



Sensor Validation {data-icon="fa-check"}
=======================================

Row {.tabset} 
-------------------------------------

### Temperature
```{r}

renderPlotly({
  
  p_temp <- plot_data_sn()
  
  validate(
    need("temperature_degree_c" %in% names(p_temp), "No temperature data found")
  )
  
  ggplotly(p_temp$temperature_degree_c) %>%
    config(
      modeBarButtonsToRemove = list("toggleSpikelines", "autoScale2d"),
      displaylogo = FALSE,
      toImageButtonOptions = list(
        format = "png",
        filename = "temperature_validation",
        width = 900, height = 500
      ))  %>%
    layout(margin = list(b = 90, l = 90))
})

```


### Dissolved Oxygen
```{r}

renderPlotly({
  
  p_do <- plot_data_sn()
  
  validate(
    need("dissolved_oxygen_percent_saturation" %in% names(p_do), 
         "No dissolved oxygen data found")
  )
  
  ggplotly(p_do$dissolved_oxygen_percent_saturation) %>%
    config(
      modeBarButtonsToRemove = list("toggleSpikelines", "autoScale2d"),
      displaylogo = FALSE,
      toImageButtonOptions = list(
        format = "png",
        filename = "dissolved_oxygen_percent_saturation_validation",
        width = 900, height = 500
      ))  #%>%
  #layout(margin = list(b = 90, l = 90))
})

``` 


### Salinity

```{r}

renderPlotly({
  
  p_sal <- plot_data_sn()
  
  validate(need("salinity_psu" %in% names(p_sal), "No salinity data found"))
  
  ggplotly(p$salinity_psu) %>%
    config(
      modeBarButtonsToRemove = list("toggleSpikelines", "autoScale2d"),
      displaylogo = FALSE,
      toImageButtonOptions = list(
        format = "png",
        filename = "salinity_validation",
        width = 900, height = 500)
    ) 
})

``` 

### Validation Data

```{r}
renderDT({
  val_data() %>% 
    datatable(
      extensions = 'Buttons',
      options = dt_options, 
      rownames = FALSE
    )
})
```

### Results

```{r}
renderDT({
  val_data() %>% 
    cv_summarise_flags(dt = FALSE)  %>% 
    datatable(
      extensions = 'Buttons',
      options = dt_options, 
      rownames = FALSE
    )
})
```

